import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:wanderhuman_app/helper/personal_info_repository.dart';
import 'package:wanderhuman_app/utilities/properties/date_formatter.dart';
import 'package:wanderhuman_app/utilities/properties/text_formatter.dart';
import 'package:wanderhuman_app/view/components/button.dart';
import 'package:wanderhuman_app/model/personal_info.dart';
import 'package:wanderhuman_app/utilities/properties/color_palette.dart';
import 'package:wanderhuman_app/utilities/properties/dimension_adapter.dart';
import 'package:wanderhuman_app/view/components/lines.dart';
import 'package:wanderhuman_app/view/home/widgets/home_utility_functions/my_animated_snackbar.dart';
import 'package:wanderhuman_app/view/login/register_account.dart';
import 'package:wanderhuman_app/view/components/textfield.dart';

class RegisterAccountForm extends StatefulWidget {
  final BorderRadius? borderRadius;
  final String email;
  final String password;

  const RegisterAccountForm({
    super.key,
    this.borderRadius,
    required this.email,
    required this.password,
  });

  @override
  State<RegisterAccountForm> createState() => _RegisterAccountFormState();
}

// // "other" in this enum means no value yet
// enum UserType { admin, caregiver, other }

// enum Gender { male, female, other }

class _RegisterAccountFormState extends State<RegisterAccountForm> {
  // UserType currentUserTypeGroupvalue = UserType.other;
  // Gender currentGroupGenderValue = Gender.other;

  // email text field will appear again if already in use
  bool isEmailAlreadyInUse = false;

  // THIS IS A LIST OF FIELDS BASED ON THE DATABASE ARCHITECTURE
  // email and password are passed from the login form
  // id is auto-generated by Firebase Authentication
  // this emailController is for just in case the email is already in use
  TextEditingController emailController = TextEditingController();
  FocusNode emailFocusNode = FocusNode();
  TextEditingController nameController = TextEditingController();
  String sexValue = "";
  TextEditingController ageController = TextEditingController();
  TextEditingController contactNumberController = TextEditingController();
  TextEditingController addressController = TextEditingController();
  // notableTrait = null, because this is for Admin and Caregiver registration Form
  // profilePictureURl is a button to select picture, not sure about this yet
  // createdAt is auto-generated base on timeStamp
  // lastUpdatedAt = createdAt
  // registeredBy = "", this is for patients only
  // assignedCaregiver = "", this is for patients only
  // deviceID = "", this is for patients only
  // email is provided by this class
  // status is automatically true by creation

  // FOR SIGN UP
  Future<bool> createUserWithEmailAndPassword() async {
    try {
      // ignore: avoid_print
      print("In THE PROCESS OF SIGNING UPPPPPPPPPPPPPPPPPPP");
      // validates if the password and comfirmPassword contains the same value
      if (widget.password.trim() == widget.password.trim()) {
        final userCredential = await FirebaseAuth.instance
            .createUserWithEmailAndPassword(
              email: emailController.text.trim(),
              password: widget.password.trim(),
            );
        // ignore: avoid_print
        print(" ✅✅✅ SIGNED UP: $userCredential");

        // to wait for the account authentication to finish first
        String userID = userCredential.user!.uid;
        toSetAndLoadNewUserCredentials(userID: userID);
      }
      return true;
    } on FirebaseAuthException catch (e) {
      showMyAnimatedSnackBar(
        context: context,
        dataToDisplay: "Email already in use.",
      );
      print("CREATE ACCOUNT ERROR: ${e.message}");
      return false;
    }
  }

  @override
  void initState() {
    super.initState();
    emailController.text = widget.email;
  }

  @override
  void dispose() {
    super.dispose();
    emailController.dispose();
    nameController.dispose();
    contactNumberController.dispose();
    addressController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      width: MyDimensionAdapter.getWidth(context),
      height: MyDimensionAdapter.getHeight(context),
      padding: EdgeInsets.only(top: 10),
      decoration: BoxDecoration(
        borderRadius: borderRadius(),
        color: MyColorPalette.formColor,
      ),
      child: Column(
        children: [
          MyLine(
            length: MyDimensionAdapter.getWidth(context) * 0.3,
            isVertical: false,
            thickness: 7,
            color: Colors.grey,
            isRounded: true,
          ),
          SizedBox(height: 20),
          MyTextFormatter.h3(
            text: "Fill in your details",
            fontsize: kDefaultFontSize + 6,
            color: Colors.blue.shade300,
          ),
          SizedBox(height: 30),
          // this textfield will only appear if the email is already in use
          if (isEmailAlreadyInUse)
            MyCustTextfield(
              labelText: "Email",
              prefixIcon: Icons.person_rounded,
              textController: emailController,
              focusNode: emailFocusNode,
              isPasswordField: false,
              borderRadius: 10,
              borderColor: MyColorPalette.borderColor,
              activeBorderColor: MyColorPalette.borderColor,
            ),
          if (isEmailAlreadyInUse) SizedBox(height: 30),
          MyCustTextfield(
            labelText: "Name",
            prefixIcon: Icons.person_rounded,
            textController: nameController,
            isPasswordField: false,
            borderRadius: 10,
            borderColor: MyColorPalette.borderColor,
            activeBorderColor: MyColorPalette.borderColor,
          ),
          Container(
            width: MyDimensionAdapter.getWidth(context),
            height: MyDimensionAdapter.getHeight(context) * 0.088,
            // color: Colors.amber,
            alignment: Alignment.center,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Padding(
                  padding: EdgeInsets.only(
                    top: MyDimensionAdapter.getHeight(context) * 0.023,
                  ),
                  child: MyCustTextfield(
                    labelText: "Age",
                    widthPercentage: 0.3,
                    isUsingStaticDimension: false,
                    prefixIcon: Icons.calendar_month_rounded,
                    textController: ageController,
                    borderRadius: 10,
                    borderColor: MyColorPalette.borderColor,
                    activeBorderColor: MyColorPalette.borderColor,
                  ),
                ),
                SizedBox(width: 10),
                sexDeterminerButton(context),
              ],
            ),
          ),
          SizedBox(height: 10),
          MyCustTextfield(
            labelText: "Contact Number",
            prefixIcon: Icons.call_rounded,
            textController: contactNumberController,
            borderRadius: 10,
            borderColor: MyColorPalette.borderColor,
            activeBorderColor: MyColorPalette.borderColor,
          ),
          SizedBox(height: 10),
          MyCustTextfield(
            labelText: "Address",
            prefixIcon: Icons.person_rounded,
            textController: addressController,
            borderRadius: 10,
            borderColor: MyColorPalette.borderColor,
            activeBorderColor: MyColorPalette.borderColor,
          ),
          SizedBox(height: 30),
          MyCustButton(
            buttonText: "CONFIRM REGISTRATION",
            buttonWidth: 250,
            buttonTextColor: Colors.white,
            onTap: () async {
              try {
                // print("✅✅✅✅✅✅");
                bool hasSuccessfullyRegistered =
                    await createUserWithEmailAndPassword();

                setState(() {
                  // to make the email field appear if the email is already in used
                  isEmailAlreadyInUse = !hasSuccessfullyRegistered;
                  emailFocusNode.requestFocus();
                });

                // only pop this sheet if the registration is successful
                if (hasSuccessfullyRegistered) Navigator.pop(context);
              } catch (e) {
                print("Error during registration: $e");
                showMyAnimatedSnackBar(
                  context: context,
                  dataToDisplay: "Email already in use.",
                );
              }
              // print("CONFIRM SIGNUP BUTTON PRESSEDDDDDDDDDDDDDDDDDDDDDDDDDD");
            },
          ),
          SizedBox(height: 10),
          // Cancel button
          cancelButton(),
        ],
      ),
    );
  }

  // when the new user account is created, this will load the name and userType of the user.
  void toSetAndLoadNewUserCredentials({required String userID}) async {
    Future.delayed(Duration(milliseconds: 100), () {
      DocumentReference docRef = FirebaseFirestore.instance
          .collection("Personal Info")
          .doc(userID);

      docRef.set({
        "userID": userID,
        // "userType": currentUserTypeGroupvalue.name,
        "name": nameController.text.trim(),
        // "sex": currentGroupGenderValue.name,
        "sex": sexValue,
        "age": ageController.text.trim(),
        "contactNumber": contactNumberController.text.trim(),
        "address": addressController.text.trim(),
        "notableBehavior": "", // empty String, as this is for patients only
        "profilePictureURL": "", // to be updated later
        "createdAt": FieldValue.serverTimestamp(),
        "lastUpdatedAt": FieldValue.serverTimestamp(),
        "registeredBy": "", // empty String, as this is for patients only
        "assignedCaregiver": "", // empty String, as this is for patients only
        "deviceID":
            "", // to be updated later, this one can be null at account creation but can have a value later on when added.
        "email": widget.email.trim(),

        // "status" : true,  // to be decided later, if ibutang ba jud ni
      });

      // FirebaseFirestore.instance.collection("Personal Info").add({
      //   // "name": nameController.text.trim(),
      //   // "userType": currentUserTypeGroupvalue.toString().split('.').last,
      //   "userID": FirebaseAuth.instance.currentUser!.uid,
      //   "userType": currentUserTypeGroupvalue.name,
      //   "name": nameController.text.trim(),
      //   "gender": currentGroupGenderValue.name,
      //   "contactNumber": contactNumberController.text.trim(),
      //   "address": addressController.text.trim(),
      //   "notableTrait":
      //       "", // empty String, as this is for patients only
      //   "profilePictureURL": "", // to be updated later
      //   "createdAt": FieldValue.serverTimestamp(),
      //   "lastUpdatedAt": FieldValue.serverTimestamp(),
      //   "registeredBy":
      //       "", // empty String, as this is for patients only
      //   "assignedCaregiver":
      //       "", // empty String, as this is for patients only
      //   "deviceID":
      //       "", // to be updated later, this one can be null at account creation but can have a value later on when added.
      //   "email": widget.email.trim(),

      //   // "status" : true,  // to be decided later, if ibutang ba jud ni
      // });
    });

    List<PersonalInfo> personsList =
        await MyPersonalInfoRepository.getAllPersonalInfoRecords();
    MyPersonalInfoRepository.getSpecificUserNameOfTheLoggedInAccount(
      personsList: personsList,
      userIDToLookFor: FirebaseAuth.instance.currentUser!.uid,
    );
  }

  Container verticalLineBorder() {
    return Container(
      width: 1,
      height: double.infinity,
      color: const Color.fromARGB(255, 123, 184, 234),
    );
  }

  // Container userTypeGroupedRadioButton() {
  //   return Container(
  //     // color: Colors.amber, // for debugging purposes only
  //     width: MyDimensionAdapter.getWidth(context) * 0.50,
  //     child: Column(
  //       children: [
  //         SizedBox(height: 6),
  //         radioListTileButtonsTitle("Role (User Type)"),
  //         myUserTypeRadioListTileBuilder(
  //           title: "Admin",
  //           enumValue: UserType.admin,
  //         ),
  //         myUserTypeRadioListTileBuilder(
  //           title: "Caregiver",
  //           enumValue: UserType.caregiver,
  //         ),
  //       ],
  //     ),
  //   );
  // }

  // Container genderGroupedRadioButton() {
  //   return Container(
  //     width: MyDimensionAdapter.getWidth(context) * 0.44,
  //     // color: Colors.orange, // for debugging purposes only
  //     child: Column(
  //       children: [
  //         SizedBox(height: 6),
  //         radioListTileButtonsTitle("Gender"),
  //         myGenderRadioListTileBuilder(title: "Male", enumValue: Gender.male),
  //         myGenderRadioListTileBuilder(
  //           title: "Female",
  //           enumValue: Gender.female,
  //         ),
  //       ],
  //     ),
  //   );
  // }

  Container sexDeterminerButton(BuildContext context) {
    double buttonWidth = MyDimensionAdapter.getWidth(context) * 0.23;
    double buttonHeight = MyDimensionAdapter.getHeight(context) * 0.063;
    return Container(
      // color: Colors.purpleAccent,
      width: MyDimensionAdapter.getWidth(context) * 0.465,
      // height: MyDimensionAdapter.getHeight(context) * 0.2,
      // margin: EdgeInsets.only(right: 18, top: 2),
      // alignment: Alignment.center,
      child: Column(
        children: [
          MyTextFormatter.p(text: "Sex", fontsize: kDefaultFontSize - 2),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              GestureDetector(
                onTap: () {
                  setState(() {
                    sexValue = "male";
                  });
                },
                child: Container(
                  width: buttonWidth,
                  height: buttonHeight,
                  decoration: BoxDecoration(
                    color: (sexValue == "male")
                        ? Colors.white60
                        : Colors.transparent,
                    border: BoxBorder.all(
                      color: (sexValue == "male")
                          ? MyColorPalette.borderColor
                          : MyColorPalette.borderColor,
                      width: (sexValue == "male") ? 1.7 : 1,
                    ),
                    borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(10),
                      bottomLeft: Radius.circular(10),
                    ),
                  ),
                  child: Center(child: Text("MALE")),
                ),
              ),

              GestureDetector(
                onTap: () {
                  setState(() {
                    sexValue = "female";
                  });
                },
                child: Container(
                  width: buttonWidth,
                  height: buttonHeight,
                  decoration: BoxDecoration(
                    color: (sexValue == "female")
                        ? Colors.white60
                        : Colors.transparent,
                    border: BoxBorder.all(
                      color: (sexValue == "female")
                          ? MyColorPalette.borderColor
                          : MyColorPalette.borderColor,
                      width: (sexValue == "female") ? 1.7 : 1,
                    ),
                    borderRadius: BorderRadius.only(
                      topRight: Radius.circular(10),
                      bottomRight: Radius.circular(10),
                    ),
                  ),
                  child: Center(child: Text("FEMALE")),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Text radioListTileButtonsTitle(String title) {
    return Text(
      title,
      overflow: TextOverflow.ellipsis,
      style: TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w600,
        color: const Color.fromARGB(255, 68, 157, 230),
      ),
    );
  }

  // Container myUserTypeRadioListTileBuilder({
  //   required String title,
  //   required dynamic enumValue,
  // }) {
  //   return Container(
  //     // color: Colors.grey,    // for debugging purposes only
  //     height: 35,
  //     margin: EdgeInsets.only(top: 5),
  //     child: RadioListTile.adaptive(
  //       activeColor: Colors.blue,
  //       fillColor: WidgetStateProperty.resolveWith(
  //         (states) => states.contains(WidgetState.selected)
  //             ? Colors.blue
  //             : const Color.fromARGB(255, 125, 184, 236),
  //       ),
  //       title: Text(
  //         title,
  //         overflow: TextOverflow.ellipsis,
  //         style: TextStyle(
  //           fontSize: 14,
  //           color: Colors.blue,
  //           fontWeight: FontWeight.w500,
  //         ),
  //       ),
  //       value: enumValue,
  //       groupValue: currentUserTypeGroupvalue,
  //       dense: true,
  //       useCupertinoCheckmarkStyle: true,
  //       onChanged: (value) {
  //         setState(() {
  //           currentUserTypeGroupvalue = value!;
  //         });
  //       },
  //     ),
  //   );
  // }

  // Container myGenderRadioListTileBuilder({
  //   required String title,
  //   required dynamic enumValue,
  // }) {
  //   return Container(
  //     // color: Colors.grey,    // for debugging purposes only
  //     height: 35,
  //     margin: EdgeInsets.only(top: 5),
  //     child: RadioListTile.adaptive(
  //       fillColor: WidgetStateProperty.resolveWith(
  //         (states) => states.contains(WidgetState.selected)
  //             ? Colors.blue
  //             : const Color.fromARGB(255, 125, 184, 236),
  //       ),
  //       title: Text(
  //         title,
  //         overflow: TextOverflow.ellipsis,
  //         style: TextStyle(
  //           fontSize: 14,
  //           color: Colors.blue,
  //           fontWeight: FontWeight.w500,
  //         ),
  //       ),
  //       value: enumValue,
  //       groupValue: currentGroupGenderValue,
  //       dense: true,
  //       useCupertinoCheckmarkStyle: true,
  //       onChanged: (value) {
  //         setState(() {
  //           currentGroupGenderValue = value!;
  //         });
  //       },
  //     ),
  //   );
  // }

  // this is just literally a Cancel button
  MyCustButton cancelButton() {
    return MyCustButton(
      onTap: () {
        setState(() {
          Navigator.pop(context);
        });
      },
      buttonText: "CANCEL",
      color: Colors.transparent,
      buttonTextFontWeight: FontWeight.w400,
      buttonTextColor: MyColorPalette.fontColorB,
      enableShadow: false,
      borderWidth: 0.5,
      borderColor: Colors.transparent,
    );
  }
}
