import 'package:flutter/material.dart';
import 'package:wanderhuman_app/components/button.dart';
import 'package:wanderhuman_app/utilities/color_palette.dart';
import 'package:wanderhuman_app/utilities/dimension_adapter.dart';
import 'package:wanderhuman_app/view/login/register_account.dart';
import 'package:wanderhuman_app/view/login/widgets/textfield.dart';

class RegisterAccountForm extends StatefulWidget {
  final BorderRadius? borderRadius;
  final String email;
  final String password;

  const RegisterAccountForm({
    super.key,
    this.borderRadius,
    required this.email,
    required this.password,
  });

  @override
  State<RegisterAccountForm> createState() => _RegisterAccountFormState();
}

// "other" in this enum means no value yet
enum UserType { admin, caregiver, other }

enum Gender { male, female, other }

class _RegisterAccountFormState extends State<RegisterAccountForm> {
  UserType currentUserTypeGroupvalue = UserType.other;
  Gender currentGroupGenderValue = Gender.other;

  // THIS IS A LIST OF FIELDS BASED ON THE DATABASE ARCHITECTURE
  // email and password are passed from the login form
  // id is auto-generated by Firebase Authentication
  TextEditingController nameController = TextEditingController();
  // userType is a Radio button
  // gender is a Radio button too
  TextEditingController contactNumberController = TextEditingController();
  TextEditingController addressController = TextEditingController();
  // notableTrait = null, because this is for Admin and Caregiver registration Form
  // profilePictureURl is a button to select picture, not sure about this yet
  // createdAt is auto-generated base on timeStamp
  // lastUpdatedAt = createdAt
  // registeredBy = "", this is for patients only
  // assignedCaregiver = "", this is for patients only
  // deviceID = "", this is for patients only
  // email is provided by this class
  // status is automatically true by creation

  @override
  Widget build(BuildContext context) {
    return Container(
      width: MyDimensionAdapter.getWidth(context),
      height: MyDimensionAdapter.getHeight(context),
      padding: EdgeInsets.only(top: 50),
      decoration: BoxDecoration(
        borderRadius: borderRadius(),
        color: MyColorPalette.lightBlue,
      ),
      child: Column(
        children: [
          MyCustTextfield(
            labelText: "Name",
            prefixIcon: Icons.person_rounded,
            textController: nameController,
            borderRadius: 10,
          ),
          SizedBox(height: 15),
          Container(
            height: 120,
            padding: EdgeInsets.only(left: 5, right: 5),
            // color: Colors.green,  // for debugging purposes only
            child: Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                userTypeGroupedRadioButton(),
                verticalLineBorder(),
                genderGroupedRadioButton(),
              ],
            ),
          ),
          SizedBox(height: 15),
          MyCustTextfield(
            labelText: "Contact Number",
            prefixIcon: Icons.call_rounded,
            textController: contactNumberController,
            borderRadius: 10,
          ),
          SizedBox(height: 15),
          MyCustTextfield(
            labelText: "Address",
            prefixIcon: Icons.person_rounded,
            textController: addressController,
            borderRadius: 10,
          ),
          SizedBox(height: 30),
          MyCustButton(
            buttonText: "CONFIRM REGISTRATION",
            buttonWidth: 250,
            buttonTextColor: Colors.white,
            onTap: () {
              // await createUserWithEmailAndPassword(); // TODO: to be configured, in order to send data to Firestore
              // print("CONFIRM SIGNUP BUTTON PRESSEDDDDDDDDDDDDDDDDDDDDDDDDDD");
            },
          ),
          SizedBox(height: 10),
          // Cancel button
          cancelButton(),
        ],
      ),
    );
  }

  Container verticalLineBorder() {
    return Container(
      width: 1,
      height: double.infinity,
      color: const Color.fromARGB(255, 123, 184, 234),
    );
  }

  Container userTypeGroupedRadioButton() {
    return Container(
      // color: Colors.amber, // for debugging purposes only
      width: MyDimensionAdapter.getWidth(context) * 0.50,
      child: Column(
        children: [
          SizedBox(height: 6),
          radioListTileButtonsTitle("Role (User Type)"),
          myUserTypeRadioListTileBuilder(
            title: "Admin",
            enumValue: UserType.admin,
          ),
          myUserTypeRadioListTileBuilder(
            title: "Caregiver",
            enumValue: UserType.caregiver,
          ),
        ],
      ),
    );
  }

  Container genderGroupedRadioButton() {
    return Container(
      width: MyDimensionAdapter.getWidth(context) * 0.44,
      // color: Colors.orange, // for debugging purposes only
      child: Column(
        children: [
          SizedBox(height: 6),
          radioListTileButtonsTitle("Gender"),
          myGenderRadioListTileBuilder(title: "Male", enumValue: Gender.male),
          myGenderRadioListTileBuilder(
            title: "Female",
            enumValue: Gender.female,
          ),
        ],
      ),
    );
  }

  Text radioListTileButtonsTitle(String title) {
    return Text(
      title,
      overflow: TextOverflow.ellipsis,
      style: TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.bold,
        color: Colors.blue,
      ),
    );
  }

  Container myUserTypeRadioListTileBuilder({
    required String title,
    required dynamic enumValue,
  }) {
    return Container(
      // color: Colors.grey,    // for debugging purposes only
      height: 35,
      margin: EdgeInsets.only(top: 5),
      child: RadioListTile.adaptive(
        title: Text(
          title,
          overflow: TextOverflow.ellipsis,
          style: TextStyle(fontSize: 14),
        ),
        value: enumValue,
        groupValue: currentUserTypeGroupvalue,
        dense: true,
        useCupertinoCheckmarkStyle: true,
        onChanged: (value) {
          setState(() {
            currentUserTypeGroupvalue = value!;
          });
        },
      ),
    );
  }

  Container myGenderRadioListTileBuilder({
    required String title,
    required dynamic enumValue,
  }) {
    return Container(
      // color: Colors.grey,    // for debugging purposes only
      height: 35,
      margin: EdgeInsets.only(top: 5),
      child: RadioListTile.adaptive(
        title: Text(
          title,
          overflow: TextOverflow.ellipsis,
          style: TextStyle(fontSize: 14),
        ),
        value: enumValue,
        groupValue: currentGroupGenderValue,
        dense: true,
        useCupertinoCheckmarkStyle: true,
        onChanged: (value) {
          setState(() {
            currentGroupGenderValue = value!;
          });
        },
      ),
    );
  }

  // this is just literally a Cancel button
  MyCustButton cancelButton() {
    return MyCustButton(
      onTap: () {
        setState(() {
          nameController.dispose();
          contactNumberController.dispose();
          addressController.dispose();
          Navigator.pop(context);
        });
      },
      buttonText: "CANCEL",
      color: Colors.white,
      buttonTextFontWeight: FontWeight.w400,
      buttonTextColor: MyColorPalette.fontColorB,
      enableShadow: false,
      borderWidth: 0.5,
      borderColor: Colors.white,
    );
  }
}
