// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWnAQx9dEpUlXN-0Xa892AR44fhvGubkc',
    appId: '1:851077489242:web:729a0f0e38678e0644ee63',
    messagingSenderId: '851077489242',
    projectId: 'wanderhuman',
    authDomain: 'wanderhuman.firebaseapp.com',
    storageBucket: 'wanderhuman.firebasestorage.app',
    measurementId: 'G-CXQG8KSB50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8bsyslCI-Q-XW6tpuSoi6LKv1ZftReYE',
    appId: '1:851077489242:android:7981814f026abfd044ee63',
    messagingSenderId: '851077489242',
    projectId: 'wanderhuman',
    storageBucket: 'wanderhuman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUGPPVABgn7gSzTic8tTm6MHZqV-HZzJM',
    appId: '1:851077489242:ios:c7587dbae14ef2bd44ee63',
    messagingSenderId: '851077489242',
    projectId: 'wanderhuman',
    storageBucket: 'wanderhuman.firebasestorage.app',
    iosBundleId: 'com.example.wanderhumanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUGPPVABgn7gSzTic8tTm6MHZqV-HZzJM',
    appId: '1:851077489242:ios:c7587dbae14ef2bd44ee63',
    messagingSenderId: '851077489242',
    projectId: 'wanderhuman',
    storageBucket: 'wanderhuman.firebasestorage.app',
    iosBundleId: 'com.example.wanderhumanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWnAQx9dEpUlXN-0Xa892AR44fhvGubkc',
    appId: '1:851077489242:web:363b8760e8b7273a44ee63',
    messagingSenderId: '851077489242',
    projectId: 'wanderhuman',
    authDomain: 'wanderhuman.firebaseapp.com',
    storageBucket: 'wanderhuman.firebasestorage.app',
    measurementId: 'G-B39PNV7RNW',
  );
}
